# tmp_dir = Rails.root.join("tmp")

Agent.create name: 'Dailson', status: :ativo, category: :tecnico
Agent.create name: 'Alice', status: :ativo, category: :coordenador
Agent.create name: 'Aline', status: :ativo, category: :voluntario

Agent.create name: 'Dailson', status: :ativo, category: :tecnico, email: 'dailson@uniaoanimal.org', password: '123456'
Agent.create name: 'Alice', status: :ativo, category: :coordenador, email: 'alice@uniaoanimal.org', password: '123456'
Agent.create name: 'Aline', status: :ativo, category: :voluntario, email: 'aline@uniaoanimal.org', password: '123456'

Sector.create name: 'Aeroporto Velho'
Sector.create name: 'Aldeia'
Sector.create name: 'Alvorada'
Sector.create name: 'Aparecida'
Sector.create name: 'Amparo'
Sector.create name: 'Área Verde'
Sector.create name: 'Caranazal'
Sector.create name: 'Cambuquira'
Sector.create name: 'Centro'
Sector.create name: 'Cohab'
Sector.create name: 'Conquista'
Sector.create name: 'Diamantino'
Sector.create name: 'Elcione Barbalho'
Sector.create name: 'Esperança'
Sector.create name: 'Fátima'
Sector.create name: 'Floresta'
Sector.create name: 'Interventoria'
Sector.create name: 'Ipanema'
Sector.create name: 'Jaderlândia'
Sector.create name: 'Jardim Santarém'
Sector.create name: 'Jutaí'
Sector.create name: 'Livramento'
Sector.create name: 'Liberdade'
Sector.create name: 'Laguinho'
Sector.create name: 'Maicá'
Sector.create name: 'Mapiri'
Sector.create name: 'Maracanã'
Sector.create name: 'Maracanã I'
Sector.create name: 'Matinha'
Sector.create name: 'Nova Vitória'
Sector.create name: 'Nova República'
Sector.create name: 'Novo Horizonte'
Sector.create name: 'Pérola do Maicá'
Sector.create name: 'Prainha'
Sector.create name: 'Rodagem'
Sector.create name: 'Salé'
Sector.create name: 'Santana'
Sector.create name: 'Santa Clara'
Sector.create name: 'Santarenzinho'
Sector.create name: 'Santíssimo'
Sector.create name: 'Santo André'
Sector.create name: 'São Cristovão'
Sector.create name: 'São Francisco'
Sector.create name: 'São José Operário'
Sector.create name: 'Uruará'
Sector.create name: 'Urumari'
Sector.create name: 'Vigia'
Sector.create name: 'Vitória-Régia'

# event_1 = Event.create(title: "3º Festival de Tortas", place: 'Praça do Pescador', date: Date.new(2018, 12, 15, 0), time: Time.new() )
# event_1.image.attach(io: File.open("#{tmp_dir}/imagens/eventos/evento_1.jpg"))